config/routes.rb
Rails.application.routes.draw do
  resources :microposts, only: [:new,:create,:destroy]
  resources :users do 
  	member do
  		get :following
  		get :followers
  	end
  end

  resources :relationships, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  get '/signup', to: 'users#new'
  
  get '/signin', to: 'sessions#new'
  
  delete '/signout', to: 'sessions#destroy'

 root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		if signed_in?
			# get the current user and store it in the @user variable
			@user = current_user
			# create an empty micropost which we can use on the form
			@micropost = current_user.microposts.build
			#get the current user's micropost feed
			@microposts = current_user.feed.paginate(page: params[:page])
			#set the feed title
			@feed_title = "Your Feed (#{@microposts.count})"
		end
	end
end

app/views/welcome/index.html.erb
<% if signed_in? %>
	<div class="row">
		<div class="col-sm-2"></div>
		<div class="col-sm-8">
			<div class="row">
				<div class="col-sm-4">
					<%= render "users/profile" %>
				</div>
				<div class="col-sm-8">
					<%= render "users/feed" %>
				</div>
			</div>
		</div>
		<div class="col-sm-2"></div>
	</div>

<% else %>
	<div class="row">
		<div class="col-sm-2">
		</div>
		<div class="col-sm-8">
		<div class="jumbotron">
			<h1>Welcome to Dropdown!</h1>
			<p>Forget Twitter, Think Dropdown!</p>
			<p>To access the wonderful feature of Dropdown, please sign in or sign up for a new account!</p>
			<p><%= link_to "Sign in", signin_path, class: "btn btn-lg btn-primary"%>
			&nbsp;
			<%= link_to "Sign up", signup_path, class: "btn btn-lg btn-success"%>
			</p>
		</div>
		<div class="col-sm-2">
		</div>
<% end %>